soulseek:
  username: saltknight823
  password: 12345e78
  listen_port: 50300

remoteConfiguration: false

relay:
  controller:
    apiKey: aBc412

directories:
  incomplete: /data/incomplete
  downloads: /data

transfers:
  download:
    slots: 3
  upload:
    slots: 10

web:
  port: 5030
  authentication:
    disabled: true

shares:
  directories:
    - /music

